# Generated by Django 4.1.6 on 2023-02-04 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categoria', models.CharField(max_length=250, verbose_name='Categoria')),
                ('Descripcion', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=250, verbose_name='Producto')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('cant', models.IntegerField(verbose_name='Existencia')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_dep', to='product.categoria', verbose_name='Categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'db_table': 'producto',
                'managed': True,
            },
        ),
    ]
